// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWX8G7gTeJWLNhElkNxjAbcBsCoQldU4',
    appId: '1:775069002777:web:10ad428d0c8451b1e10e88',
    messagingSenderId: '775069002777',
    projectId: 'todo-gen-ia',
    authDomain: 'todo-gen-ia.firebaseapp.com',
    storageBucket: 'todo-gen-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvwil7XysACCdMR4FiC2UwPdF2v-o0vrI',
    appId: '1:775069002777:android:56f68e05ddf3d00be10e88',
    messagingSenderId: '775069002777',
    projectId: 'todo-gen-ia',
    storageBucket: 'todo-gen-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCECCz74ADuP0eVQMnEsal8qvnm3G0g_Kk',
    appId: '1:775069002777:ios:cf583ff80c056a64e10e88',
    messagingSenderId: '775069002777',
    projectId: 'todo-gen-ia',
    storageBucket: 'todo-gen-ia.firebasestorage.app',
    iosBundleId: 'com.example.usedev',
  );
}
